### ISSUE TITLE
Error 500 calling Google searchAnalytics

### ISSUE THREAD

**Issue by PatriceParis** [OuestFrance-Multimedia/Google-Search-Console-Archive#3]
Salut !

Merci d'avoir mis ce projet à dispo. 

Lorsque j'exécute "cron.php 2016-12-20", le script semble tourner correctement puis au bout d'un moment : PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/webmasters/v3/sites/http%3A%2F%2Fwww.observatoiredelafranchise.fr/searchAnalytics/query: (500) {
 "error": {
  "code": 500,
  "message": null
 }
}
' in /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Http/REST.php:110

Merci par avance,
Patrice
--
Extrait de la console :
--
$ php cron.php 2016-12-20
                   .
                 ....8ob.
              o88888888888b.
          ..o888888888888888b..
          888888888888888P""888P
         8888888888888888888888.
        d88888888888888888888888bc.
       o8888888888888888"   ""38888Poo..
      .8888888888P888888        "38888888
      88888888888 8888888eeeeee.   ""38"8
     P" 888888888 """""       `""o._.oP
        8888888888.
        88888888888
        '888888888 8b.
         "88888888b  """"3booooooo..
          "888888888888888b         "b.
           "8888888888888888888888b    "8
            "8888888888888888888888888   b
                ""888888888888888888888  c
                   "8888888888888888888  P
                    "88888888888888888888"
                    .88888888888888888888
                   .88888 ><)))°> 88888P    Google Console API Query
                 od888888888888888888P"

Configuration :
  Database : root@localhost:3306/google_search_console
Usage : php cron.php $from
        $from : days of data history to check from now
Docs : https://developers.google.com/webmaster-tools/v3/searchanalytics/query

Calling Search Console API ............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/webmasters/v3/sites/http%3A%2F%2Fwww.observatoiredelafranchise.fr/searchAnalytics/query: (500) {
 "error": {
  "code": 500,
  "message": null
 }
}
' in /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Http/REST.php:110
Stack trace:
#0 /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Http/REST.php(62): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#2 /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Task/Runner.php(174): call_user_func_array(Array, Array)
#3 /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Http/REST.php(46): Google_Task_Runner->run()
#4 /var/www/local.dev/Google-Search-Console-Arch in /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Http/REST.php on line 110

Fatal error: Uncaught exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/webmasters/v3/sites/http%3A%2F%2Fwww.observatoiredelafranchise.fr/searchAnalytics/query: (500) {
 "error": {
  "code": 500,
  "message": null
 }
}
' in /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Http/REST.php:110
Stack trace:
#0 /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Http/REST.php(62): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#2 /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Task/Runner.php(174): call_user_func_array(Array, Array)
#3 /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Http/REST.php(46): Google_Task_Runner->run()
#4 /var/www/local.dev/Google-Search-Console-Arch in /var/www/local.dev/Google-Search-Console-Archive-master/vendor/google/apiclient/src/Google/Http/REST.php on line 110

**Comment by elijaa** [comment]
Bonjour !

Pouvez vous plutôt exécuter 
> php cron.php 90
Il s'agit du nombre de jour d'histo à aller chercher par de la date.

Néanmoins ca devrais pas changer beaucoup de chose, l'erreur en plus n'est pas explicite.
Je vais essayer de la reproduire.
